# NOTES
# Run `pre-commit autoupdate` to update to the latest version of hooks
# By default pre-commit only runs against changed files. To run against all riles run 'pre-commit run --all-files'

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
      # root
      - id: poetry-check
        language_version: python3.11
      - id: poetry-lock
        language_version: python3.11
      - id: poetry-export
        language_version: python3.11

      # backend_fastapi
      - id: poetry-check
        args: ['-C', './backend_fastapi']
        language_version: python3.11
      - id: poetry-lock
        args: ['-C', './backend_fastapi']
        language_version: python3.11
      - id: poetry-export
        args:
          [
            '-C',
            './backend_fastapi',
            '-f',
            'requirements.txt',
            '-o',
            './backend_fastapi/requirements.txt'
          ]
        language_version: python3.11

      # python workspace
      - id: poetry-check
        args: ['-C', './python_workspace']
        language_version: python3.10
      - id: poetry-lock
        args: ['-C', './python_workspace']
        language_version: python3.10
      - id: poetry-export
        args:
          [
            '-C',
            './python_workspace',
            '-f',
            'requirements.txt',
            '-o',
            './python_workspace/requirements.txt'
          ]
        language_version: python3.10

      # streamlit app
      - id: poetry-check
        args: ['-C', './streamlit_app']
        language_version: python3.10
      - id: poetry-lock
        args: ['-C', './streamlit_app']
        language_version: python3.10
      - id: poetry-export
        args:
          [
            '-C',
            './streamlit_app',
            '-f',
            'requirements.txt',
            '-o',
            './streamlit_app/requirements.txt'
          ]
        language_version: python3.10

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.7
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
