[tool.poetry]
name = "forestbot"
version = "0.1.0"
description = ""
authors = ["Guillaume Soto", "Tony Lopes" ]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.17.1"
langchain = {extras = ["docarray"], version = "^0.1.16"}
langchain-openai = "^0.1.3"
python-dotenv = "^1.0.1"
panel = "^1.4.1"
param = "^2.1.0"
ipykernel = "^6.29.4"
pypdf = "^4.2.0"
streamlit = "^1.33.0"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
