[tool.poetry]
name = "forestbot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "src/api/*.py"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.4"
Flask = "^3.0.3"
langchain = "^0.1.16"
langchain-openai = "^0.1.3"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.7"
pre-commit = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
